### ISSUE TITLE
The application crushing always on Android 7.1.2

### ISSUE THREAD

**Issue by ypsilonmeister** [aragaer/jtt_android#19]
I updated my Nexus 6p, Android 7.1.2, then jtt is not working.
Uninstallation and reinstallation did not solve this problem.

**Comment by aragaer** [comment]
Can I see logcat?

**Comment by ypsilonmeister** [comment]
Hummm. I set "developer mode" and connect to PC, run adb logcat  and run JTT... It was work...
I do not know what is going on, but it was solved on my side.

Will close this issue.

**Comment by aragaer** [comment]
It seems that your crash was actually reported on google play developer console. It was a real error which should be fixed already in the latest beta.
