### ISSUE TITLE
Start of day

### ISSUE THREAD

**Issue by c933103** [aragaer/jtt_android#31]
Avcording to my understanding, in Japanese tradition, a new day usually start on sunrise, instead of sunset which the app currently show?

**Comment by ilya-konovalov** [comment]
You are probably looking at the "Today" tab. That might be somewhat non-intuitive but it actually shows three "day-or-night" periods. During day it shows the night before, the day itself and the night after. During night it shows day-night-day.

Initially I planned that tab to be an infinite scroll to whatever date you'd like with a way to return back to current day, but in the end never implemented that.

**Comment by aragaer** [comment]
You are probably looking at the "Today" tab. That might be somewhat non-intuitive but it actually shows three "day-or-night" periods. During day it shows the night before, the day itself and the night after. During night it shows day-night-day.

Initially I planned that tab to be an infinite scroll to whatever date you'd like with a way to return back to current day, but in the end never implemented that.

**Comment by c933103** [comment]
I see. Thanks for your reply.
